language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- dist/bin/premake5 gmake
- cd build
- make config=releaseshared_x86_64 all
- cd ../

after_success:
- bin/x86_64/releaseShared/unittest
- bin/x86_64/releaseShared/scratch

